#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan for NEWIFI3-tiny

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: NEWIFI3
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        ################################################################################################
        #最小化系统及更新设置
        sed -i '/INCLUDE/{s/=y/=n/}' .config                    #关闭所有INCLUDE
        sed -i '/LANG_CN/{s/=n/=y/}' .config                    #设置默认语言为中文
        sed -i '7c size_tmp="128M"' user/scripts/dev_init.sh    #调整/tmp分区为128MB
        sed -i '3c FIRMWARE_BUILDS_REV=20210326' versions.inc   #更新版本日期
        sed -i '/2011-2019/{s/2019/2021/}' user/www/Makefile    #过年好
        sed -i '1c SRC_NAME = htop-3.0.5' user/htop/Makefile    #更新htop
        sed -i '2c SRC_URL = https://bintray.com/htop/source/download_file?file_path=htop-3.0.5.tar.gz' user/htop/Makefile
        cp -f $GITHUB_WORKSPACE/vmake user/v2ray/Makefile
        cp -f $GITHUB_WORKSPACE/dnsmasq user/dnsmasq/Makefile 
        ################################################################################################
        #删除注释以关闭更多不需要的功能支持，默认保留
        #sed -i '/ENABLE_IPV6/{s/=y/=n/}' .config               #IPV6支持
        #sed -i '/ENABLE_USB/{s/=y/=n/}' .config                 #USB接口相关功能
        sed -i '/ENABLE_UFSD/{s/=y/=n/}' .config                #NTFS文件系统
        ################################################################################################
        #添加基础工具
        sed -i '/_OPENSS/{s/=n/=y/}' .config
        sed -i '/IPSET/{s/=n/=y/}' .config
        sed -i '/CURL/{s/=n/=y/}' .config
        sed -i '/HTOP/{s/=n/=y/}' .config
        sed -i '/IPERF3/{s/=n/=y/}' .config
        ################################################################################################
        #默认扩展功能，注释以禁用
        sed -i '/SFTP/{s/=n/=y/}' .config       #SFTP文件访问
        ################################################################################################
        #额外扩展功能，注释以禁用
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config     #SS plus+
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=y" >> .config           #V2ray二进制文件(4.8M)
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config        #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=y" >> .config     #smartdns二进制文件
        echo "CONFIG_FIRMWARE_WEBUI_HIDE_VPN=y" >> .config         #关闭ASUS VPN服务
        ################################################################################################
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-NEWIFI3-tiny
        path: /opt/images
