#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan for NEWIFI-MINI

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/keke1023/Padavan.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: NEWIFI-MINI
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        ################################################################################################
        #最小化系统及更新设置
        sed -i '/INCLUDE/{s/=y/=n/}' .config                    #关闭所有INCLUDE
        sed -i '/LANG_CN/{s/=n/=y/}' .config                    #设置默认语言为中文
        sed -i '7c size_tmp="32M"' user/scripts/dev_init.sh    #调整/tmp分区为32MB
        sed -i '3c FIRMWARE_BUILDS_REV=lissom' versions.inc   #更新版本日期
        sed -i '2c FRP_VER := 0.38.0' user/frp/Makefile    #更新frp
        sed -i '4c SRC_ARIA_NG_NAME=AriaNg-1.2.4-AllInOne' user/aria2/Makefile  #更新AriaNg
        sed -i '5c SRC_ARIA_NG_URL=https://github.com/mayswind/AriaNg/releases/download/1.2.4/AriaNg-1.2.4-AllInOne.zip' user/aria2/Makefile
        wget https://bitbucket.org/padavan/rt-n56u/raw/32a93db4026cc2cff585d7008373432d888fc1aa/trunk/user/www/n56u_ribbon_fixed/bootstrap/img/asus_logo.png -O user/www/n56u_ribbon_fixed/bootstrap/img/asus_logo.png
        ################################################################################################
        #删除注释以关闭更多不需要的功能支持，默认保留
        sed -i '/ENABLE_UFSD/{s/=y/=n/}' .config                #NTFS文件系统
        ################################################################################################
        #恢复基础工具
        sed -i '/_OPENSS/{s/=n/=y/}' .config
        sed -i '/IPSET/{s/=n/=y/}' .config
        sed -i '/CURL/{s/=n/=y/}' .config
        sed -i '/HTOP/{s/=n/=y/}' .config
        sed -i '/IPERF3/{s/=n/=y/}' .config
        sed -i '/OPENVPN/{s/=n/=y/}' .config
        sed -i '/TTYD/{s/=n/=y/}' .config
        sed -i '/FRPC/{s/=n/=y/}' .config
        ################################################################################################
        #默认扩展功能，注释以禁用
        sed -i '/SFTP/{s/=n/=y/}' .config       #SFTP文件访问
        sed -i '/HDPARM/{s/=n/=y/}' .config     #硬盘休眠
        ################################################################################################
        #额外扩展功能，注释以禁用
        #echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config        #smartdns
        #echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=y" >> .config        #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config        #smartdns
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config        #zerotier (1.3M)
        ################################################################################################
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-NEWIFI-MINI
        path: /opt/images
