#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan for YK-L1

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: YK-L1
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        ################################################################################################
        #最小化系统及更新设置
        cp -f $GITHUB_WORKSPACE/asus_logo.png  user/www/n56u_ribbon_fixed/bootstrap/img/asus_logo.png   #替换logo
        sed -i '/INCLUDE/{s/=y/=n/}' .config                    #关闭所有INCLUDE
        sed -i '/LANG_CN/{s/=n/=y/}' .config                    #设置默认语言为中文
        sed -i '7c size_tmp="32M"' user/scripts/dev_init.sh    #调整/tmp分区为32MB
        sed -i '3c FIRMWARE_BUILDS_REV=20220815' versions.inc   #更新版本日期
        sed -i '/2011-2019/{s/2019/2022/}' user/www/Makefile    #过年好
        sed -i '1c SRC_NAME = htop-3.0.2' user/htop/Makefile    #更新htop
        sed -i '2c SRC_URL = http://sources.buildroot.net/htop/htop-3.0.2.tar.gz' user/htop/Makefile
        ################################################################################################
        #添加基础工具
        sed -i '/_OPENSS/{s/=n/=y/}' .config
        sed -i '/IPSET/{s/=n/=y/}' .config
        sed -i '/CURL/{s/=n/=y/}' .config
        sed -i '/HTOP/{s/=n/=y/}' .config
        sed -i '/IPERF3/{s/=n/=y/}' .config
        ################################################################################################
        #默认扩展功能，注释以禁用
        #sed -i '/VLMCSD/{s/=n/=y/}' .config     #KMS激活服务
        sed -i '/SFTP/{s/=n/=y/}' .config       #SFTP文件访问
        sed -i '/HDPARM/{s/=n/=y/}' .config     #硬盘休眠
        sed -i '/PARTED/{s/=n/=y/}' .config     #分区工具
        sed -i '/SMBD/{s/=n/=y/}' .config       #Samba局域网共享
        sed -i '/SYSLOG/{s/=y/=n/}' .config     #关闭Samba访问日志
        sed -i '782,783d' user/rc/net.c         #解决ios缓慢问题
        cp -f $GITHUB_WORKSPACE/tailscale  user/zerotier/Makefile
        ################################################################################################
        #echo "CONFIG_FIRMWARE_INCLUDE_DDNSTO=y" >> .config #ddnsto  ~0.5M
        #echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config #zerotier ~1.3M
        ################################################################################################
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-YK-L1
        path: /opt/images
